spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./data/data
    username: su
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
  tomcat:
    basedir:
      /tmp
  adminpass: adminpass