spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./data/data
    username: soramame
    password: nobokemaker
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
  tomcat:
    basedir:
      /tmp